version: "3.9"

services:
  backend:
    build:
      dockerfile: Development.Dockerfile
      context: backend/
    ports:
      - "5000:80"
  frontend:
    build:
      dockerfile: Development.Dockerfile
      context: frontend/
    ports:
      - "80:3000"
